import Config

# Configure your database
config :open_mes, OpenMes.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "open_mes_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :open_mes, OpenMesWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "21IwkZiU6xJllj66zstpExHPQYK3wPgmvx1u8ev+ff2hN37imnYdLccZEQG/5XlB",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:open_mes, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:open_mes, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :open_mes, OpenMesWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/open_mes_web/(controllers|live|components)/.*(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :open_mes, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include HEEx debug annotations as HTML comments in rendered markup
  debug_heex_annotations: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# ── EXT-1 설비 수집 — 개발에서 켜기(TimescaleDB 컨테이너 전제) ──────────────
config :open_mes, OpenMes.Ingest,
  enabled: true,
  sink: OpenMes.Ingest.Sink.NoopSink,
  device_tokens: ["dev-device-token"]

# ── EXT-2 멀티미디어 — 개발에서 켜기(MinIO 컨테이너 전제) ──────────────────
config :open_mes, OpenMes.Media,
  enabled: true,
  object_store: OpenMes.Media.ObjectStore.S3ObjectStore,
  sink: OpenMes.Media.Sink.NoopSink,
  bucket: "open-mes-media",
  watch_roots: []

# ── ex_aws (MinIO) — 개발 엔드포인트 ───────────────────────────────────────
config :ex_aws,
  access_key_id: "minioadmin",
  secret_access_key: "minioadmin"

config :ex_aws, :s3,
  scheme: "http://",
  host: "localhost",
  port: 9000

# ── 애드온 — 개발에서 전부 켜서 카탈로그 "열기" 링크를 모두 확인 ───────────
config :open_mes, OpenMes.Addons.DailyProductionSummary, enabled: true

# 외부 데모 확장(open_mes_ext_demo) — 기본 비활성(설계 30 증명 후 유지). 켜려면:
#   config :open_mes_ext_demo, OpenMesExtDemo.Extension, enabled: true
# 켜면 deps 한 줄만으로 카탈로그 카드 + /extensions/demo 라우트가 자동 노출된다(코어 수정 0).
